
-- Coaching tips static database
CREATE TABLE public.coaching_tips (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tag text NOT NULL UNIQUE,
  game public.game_type NOT NULL,
  problem text NOT NULL,
  description text NOT NULL,
  why text NOT NULL,
  fix text NOT NULL,
  training text NOT NULL,
  video_title text NOT NULL,
  video_url text NOT NULL,
  difficulty text NOT NULL CHECK (difficulty IN ('beginner','intermediate','advanced')),
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.coaching_tips TO anon, authenticated;
GRANT ALL ON public.coaching_tips TO service_role;
ALTER TABLE public.coaching_tips ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tips public read" ON public.coaching_tips FOR SELECT USING (true);

-- Per-user progression on tips
CREATE TABLE public.user_coaching_progress (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  tip_tag text NOT NULL REFERENCES public.coaching_tips(tag) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','in_progress','resolved')),
  last_detected_at timestamptz,
  detections_since_progress int NOT NULL DEFAULT 0,
  clean_analyses_since_progress int NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, tip_tag)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_coaching_progress TO authenticated;
GRANT ALL ON public.user_coaching_progress TO service_role;
ALTER TABLE public.user_coaching_progress ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own progress select" ON public.user_coaching_progress FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "own progress insert" ON public.user_coaching_progress FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "own progress update" ON public.user_coaching_progress FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "own progress delete" ON public.user_coaching_progress FOR DELETE USING (auth.uid() = user_id);
CREATE TRIGGER trg_user_coaching_progress_updated BEFORE UPDATE ON public.user_coaching_progress FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Store matched tags on each analysis
ALTER TABLE public.analyses ADD COLUMN IF NOT EXISTS tip_tags jsonb NOT NULL DEFAULT '[]'::jsonb;

-- Seed Valorant + LoL tips
INSERT INTO public.coaching_tips (tag, game, problem, description, why, fix, training, video_title, video_url, difficulty) VALUES
('VAL-01','valorant','Mauvais placement du viseur (Crosshair Placement)','Viser le sol, les pieds des ennemis ou les mauvais angles lors des déplacements, forçant à faire de grands ajustements réflexes pour tirer dans la tête.','Par habitude visuelle de regarder le sol pour se repérer, ou par manque de concentration et de connaissance de la hauteur de la tête des agents sur les différentes textures de la carte.','Garder systématiquement le viseur à hauteur de tête (en s''aidant des repères visuels du décor comme les caisses ou les lignes de texture) et pré-viser activement les angles avant de s''exposer.','Entrez dans le champ de tir (The Range) en mode Practice. Déplacez-vous latéralement entre les obstacles tout en maintenant votre viseur collé sur la tête d''un bot immobile. Ensuite, faites un Deathmatch uniquement au Guardian en vous forçant à ne tirer que si votre viseur est déjà sur la tête de l''adversaire sans faire de grand flick.','Get PERFECT AIM With Crosshair Placement in 10 MINUTES! - Valorant Guide','https://www.youtube.com/watch?v=gp1hcJAg8ZA','beginner'),
('VAL-02','valorant','S''accroupir par panique à chaque combat (Crouch Spraying)','S''accroupir instantanément dès qu''un combat s''engage et tirer en continu (spray), rendant le joueur immobile et extrêmement facile à éliminer, tout en ruinant son contrôle de recul à moyenne et longue distance.','C''est un réflexe de panique né de l''habitude de vouloir stabiliser l''arme à tout prix ou d''une mauvaise transition depuis d''autres jeux de tir tactiques.','Apprendre à faire des rafales courtes (bursts) de 2 à 3 balles suivies d''un déplacement latéral (strafe) pour rester mobile et difficile à cibler, puis ne s''accroupir qu''occasionnellement pour casser la ligne de tir.','Jouez 2 à 3 parties de Deathmatch en ayant totalement réassigné la touche Crouch sur la touche de sélection du couteau. Chaque fois que vous tenterez de vous accroupir par réflexe, vous sortirez votre couteau, ce qui vous forcera à éliminer cette mauvaise habitude.','HOW TO STOP CROUCHING IN VALORANT! | EVERYTHING CROUCHING EXPLAINED!','https://www.youtube.com/watch?v=NlBC4KSE_Fs','beginner'),
('VAL-03','valorant','Coller les murs en prenant une ligne (Avantage d''angle)','Se tenir trop près du mur ou du coin de l''obstacle duquel on décale. L''adversaire plus éloigné du coin vous voit apparaître en premier sur son écran, vous éliminant avant même que vous ne puissiez le voir.','Le désir intuitif de se cacher derrière un obstacle pousse à s''y coller physiquement, sans comprendre la géométrie des lignes de vue en 3D.','Décalez toujours en vous éloignant le plus possible du mur ou de l''obstacle de coin. Plus vous êtes loin du coin par rapport à votre adversaire, plus vous le verrez en premier.','En partie personnalisée avec un ami, demandez-lui de tenir un angle (ex: Haven long A). Décalez en étant collé au mur, puis recommencez en étant le plus reculé possible. Constatez la différence de timing d''apparition et appliquez ce recul en partie classée.','GET MORE KILLS with ANGLE & PEEKER''S ADVANTAGE in Valorant','https://www.youtube.com/watch?v=pbGloXoHw3g','intermediate'),
('VAL-04','valorant','Mauvaise gestion de l''économie individuelle et collective','Forcer l''achat d''armes chères lors d''un round d''éco alors que l''équipe économise, ou économiser quand toute l''équipe force.','Manque de communication, absence de vérification du panneau d''achat (Tab/B) et envie impulsive de faire des éliminations chaque round au détriment de la stratégie collective.','Synchroniser systématiquement ses achats avec l''équipe : acheter ensemble (Full Buy), économiser ensemble (Eco) ou faire un Half Buy pour garantir 3900 crédits au round suivant.','Pendant vos 5 prochaines parties, imposez-vous comme règle de ne jamais rien acheter avant d''avoir regardé l''argent des coéquipiers. Annoncez à voix haute le plan : « on éco tous » ou « on achète tous ». Ne dérogez jamais au buy collectif.','VALORANT Economy Guide: Everything You Need to Know!','https://www.youtube.com/watch?v=9--6j8IRhos','beginner'),
('VAL-05','valorant','Ignorer la minimap (Minimap Blindness)','Ne regarder la minimap que très rarement, manquant des informations cruciales : positions repérées, direction des tirs, icônes d''agents, menant à des décisions tardives ou erronées.','Hyper-focalisation sur le viseur principal et l''écran central par peur de se faire surprendre.','Prendre l''habitude de jeter un coup d''œil à la minimap toutes les 3-5 secondes dès que l''on est à l''abri, et l''utiliser pour anticiper les mouvements grâce aux cônes de vision des alliés.','Configurez la minimap : Fixed, Keep Player Centered OFF, taille 0.9, zoom 0.9. Forcez-vous à regarder la minimap à chaque rechargement ou repli derrière une couverture sûre.','How to have Radiant map awareness','https://www.youtube.com/watch?v=FmQRSjmJVQY','intermediate'),
('VAL-06','valorant','Absence de Deadzoning et mauvais mouvement de combat','Rester statique ou faire de trop longs déplacements continus pendant un duel, ou tirer en bougeant, ce qui rend les tirs imprécis et fait de vous une cible facile.','Manque de coordination œil-main et méconnaissance du Deadzoning (tirer pile au moment où la vitesse s''annule lors d''un changement de direction de strafe).','Maîtriser le strafe de combat : pas de côté rapides A/D et tirer une à deux balles précisément au point d''arrêt (vitesse nulle), tirs 100% précis tout en restant en mouvement.','Dans The Range avec bots immobiles, faites des déplacements latéraux continus. Synchronisez vos tirs (1 balle de Vandal/Sheriff) au moment exact du changement de touche. Le graphique d''erreur de tir doit afficher uniquement des barres jaunes.','Stop moving like a noob | Movement Mastery pt. 1','https://www.youtube.com/watch?v=nm_n2lvHbsM','advanced'),
('LOL-01','lol','Mauvaise gestion des vagues de sbires (Wave Management)','Pousser la vague en continu sans raison, ou ne pas la pousser quand c''est nécessaire, vous mettant à la merci des ganks et perdant or et XP.','Envie instinctive de taper les sbires en continu ou absence de compréhension des états de la wave (Slow Push, Fast Push, Freeze).','Apprendre les bases : slow push pour accumuler de gros paquets et dive sous tour ennemie, ou freeze près de sa propre tour pour rester en sécurité et priver l''ennemi de sbires.','Dans le Practice Tool, entraînez-vous à maintenir le freeze juste avant la portée de votre tourelle pendant 10 minutes consécutives. Ne donnez que le last hit et gardez l''équilibre du nombre de sbires.','The Ultimate Wave Management Guide for League of Legends','https://www.youtube.com/watch?v=Sbt6imQbTSs','intermediate'),
('LOL-02','lol','Absence totale de vision de jeu et de surveillance de la minimap','Jouer avec la caméra verrouillée sur son champion, ne jamais regarder la minimap, se faire surprendre par les ganks du jungler ennemi et ignorer les escarmouches alliées.','Sensation de confort avec la caméra verrouillée et difficulté à partager son attention entre les sbires et la carte.','Déverrouiller sa caméra (touche Y) et s''obliger à jeter un œil à la minimap entre chaque last-hit.','Forcez-vous à regarder la minimap après chaque sbire tué (1 last-hit -> 1 regard). Utilisez un métronome réglé sur un bip toutes les 5 secondes et regardez la carte à chaque bip.','How To ACTUALLY Improve MAP AWARENESS : Never Die To A Gank Again','https://www.youtube.com/watch?v=PoAlm7A0rDA','beginner'),
('LOL-03','lol','Mauvais timings de retour à la base (Recall Timings)','Rentrer à la base au mauvais moment (vague qui pousse vers votre tour, grosse vague ennemie qui arrive), vous faisant perdre des niveaux entiers et des vagues sous tour.','Besoin pressant de dépenser son or ou de récupérer ses PV sans analyser l''état actuel et futur de la vague.','N''initier un recall que dans deux cas idéaux : après avoir crash une grosse vague sous la tour ennemie (idéalement avec un sbire canon), ou quand la vague ennemie pousse lentement vers vous et que la TP est disponible.','Appliquez la règle : « ne rappeler que si vous avez poussé sous la tour ennemie ou si la vague pousse vers vous sans perdre de sbire canon ». Notez à chaque fin de partie les recalls qui ont coûté plus de 3 sbires.','WIN LANE by RECALLING correctly','https://www.youtube.com/shorts/A2JpxsjQHDw','beginner'),
('LOL-04','lol','Ignorer la posture d''échange en phase de ligne (Trading Stance)','Subir des dégâts gratuits en tentant de last-hit, ou ne pas punir l''adversaire qui s''avance pour son propre last-hit.','Focaliser toute son attention sur ses propres sbires sans surveiller la position et le timing d''attaque de l''adversaire.','Maîtriser la Trading Stance : se positionner sur le sbire allié presque mort. Dès que l''adversaire s''avance pour le coup de grâce, il est bloqué dans son animation : profitez-en pour l''attaquer gratuitement.','Concentrez-vous exclusivement sur la barre de vie de vos sbires. Dès qu''un sbire allié est bas et que l''adversaire approche, lancez-lui une compétence ou auto-attaque sans rater vos propres CS.','Leaguecraft 101 Episode 1 Trading Stance','https://www.youtube.com/watch?v=iko2tqmDpJQ','advanced'),
('LOL-05','lol','Mauvais positionnement et sélection de cible en Teamfight','S''exposer prématurément aux CC en tant que carry, ou courir tête baissée vers les carries adverses en abandonnant ses propres carries en tant que tank/bruiser.','Tunnel vision en teamfight : on court vers l''ennemi le plus visible ou le plus low HP sans réfléchir à son rôle ou aux menaces clés.','Identifier son rôle avant le combat : carries restent derrière la frontline et tapent la cible la plus proche/sûre en évitant les CC clés ; tanks engagent une cible isolée ou peel les carries contre les assassins.','Avant chaque teamfight (Dragon/Baron), énumérez mentalement les 2 sorts de CC ennemis qui peuvent vous one-shot (ult Malphite, cage Veigar...). Ne rentrez pas en portée tant qu''ils ne sont pas utilisés sous vos yeux.','How to Teamfight in League of Legends: ULTIMATE Team Fighting Guide!','https://www.youtube.com/watch?v=bYU3Y4G4uKc','intermediate'),
('LOL-06','lol','Mauvais placement et gestion de la vision (Warding)','Placer des wards au hasard sans réfléchir aux entrées de jungle ou aux objectifs, ou oublier d''utiliser son altération/brouilleur, laissant l''équipe aveugle.','Manque d''attention à la carte et habitude de warder uniquement quand on a peur plutôt que de manière préventive pour suivre le jungler adverse.','Placer ses wards aux intersections clés de la jungle ennemie ou dans les pixel brushes de rivière pour repérer le jungler en avance. Toujours coordonner la vision autour des objectifs (Dragon/Baron) 1 minute en amont.','Dans le Practice Tool, entraînez-vous à warder à travers les murs vers les buissons clés. En partie réelle, visez un score de vision d''au moins 1,5x la durée de la partie (45 sur une partie de 30 min).','Warding Explained In 3 Minutes - A Guide for League of Legends','https://www.youtube.com/watch?v=65v9vSxkoJ4','beginner');
